#!/usr/bin/env bash
# Seed the v1.2.0 localized About content into the local Vancine backend
# (SQLite) so the /about page renders the real Vancine copy instead of
# the upstream new-api fallback. This is the recommended local procedure for
# verifying the v1.2.0 About page contract on a real local backend.
#
# This is a development-only tool for **one-time, throwaway local SQLite
# verification**. It writes a small JSON blob into a single option key
# (`About`) on a local backend. It is **not** a production write shortcut
# and is not wired into any deployment automation.
#
# Usage:
#   1. Start the local backend on a port that does not collide with the
#      frontend dev server. SQLite + no Redis is enough for a one-off
#      local About verification.
#   2. Initialize the root user once: POST /api/setup with a strong
#      random password generated by Python `secrets` (see README).
#   3. Run this script with the same password in the environment:
#         VANCINE_ROOT_PASSWORD=... \
#           scripts/seed-about-content/seed.sh
#      The script logs in as the root user, PUTs the content to
#      /api/option, and then GETs /api/about with both
#      Accept-Language: en and Accept-Language: zh-CN and verifies the
#      readback matches seeds.json character-for-character. There is no
#      override switch — the script is local-only by design.
#
# Safety:
#   * VANCINE_ROOT_PASSWORD MUST be set in the environment. There is no
#     default password — leaving the variable unset is a hard error.
#   * VANCINE_BACKEND_BASE is unconditionally restricted to loopback.
#     The script parses the URL with Python urllib.parse, then validates
#     the host with Python ipaddress: the host must be exactly
#     "localhost" (case-insensitive) or it must be parseable as an IP
#     literal for which is_loopback returns true. There is no DNS
#     resolution. There is no override environment variable. URLs that
#     carry any '@' in the netloc (including an empty userinfo segment
#     like "http://@localhost:3000"), any '?' in the raw URL
#     (including a bare '?' with no query body), any '#' in the raw
#     URL (including a bare '#' with no fragment body), or a non-root
#     path are all rejected before any HTTP request is made, to avoid
#     URL-construction ambiguity.
#   * All curl calls in this script pass --noproxy '*'. Even if the
#     caller has set http_proxy / https_proxy / HTTP_PROXY /
#     HTTPS_PROXY / ALL_PROXY in the environment, the script
#     bypasses every proxy and connects directly to the loopback
#     target. The root password, the access token, and the About
#     body therefore never traverse an external proxy.
#   * No sensitive temp files. The script does not call mktemp(1) and
#     does not register an EXIT trap. The login JSON and the option
#     JSON are streamed from Python's stdout to curl's stdin via
#     `--data-binary @-`, so the password and the About body never
#     land on disk in a temp file. The access token is sent in the
#     curl config built by a short-lived `<(printf ...)` process
#     substitution, so it never appears on the curl command line.
#   * The password, the access token, and the About body are never
#     passed to a child process as a command-line argument. They
#     travel as stdin payloads (for bodies) or as content of an
#     ephemeral process-substitution file descriptor (for the
#     Authorization header).
#   * The script only writes the `About` key to /api/option. It does
#     not touch the local SQLite file, the root user record, the
#     session token, or any frontend state.
#   * PUT is verified by parsing the response JSON and requiring
#     success === true. The readback is then performed with two
#     different Accept-Language headers (en, zh-CN) and the resulting
#     data fields are compared character-for-character with the
#     corresponding keys in seeds.json. The final sample printed to
#     stdout reuses the already-verified zh-CN readback body; no
#     second GET is issued.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEED_FILE="${SCRIPT_DIR}/seeds.json"
BACKEND_BASE="${VANCINE_BACKEND_BASE:-http://localhost:3000}"
ROOT_USER="${VANCINE_ROOT_USER:-root}"

# VANCINE_ROOT_PASSWORD is required — there is no default. A missing or
# empty value aborts before any network call is made, so an unattended
# invocation can never silently fall back to a weak password.
if [[ -z "${VANCINE_ROOT_PASSWORD+x}" || -z "${VANCINE_ROOT_PASSWORD}" ]]; then
  echo "error: VANCINE_ROOT_PASSWORD must be set in the environment" >&2
  echo "       (this script will not run with a default password)" >&2
  echo "       generate one with:  python3 -c 'import secrets; print(secrets.token_urlsafe(32))'" >&2
  exit 64
fi

# Loopback enforcement: parse the URL with Python urllib.parse and
# check the host with Python ipaddress. We accept the literal
# "localhost" (case-insensitive) or an IP literal for which
# is_loopback returns true. There is no DNS resolution and no override.
# We also reject URLs that carry any '@' in the netloc (including
# the empty-userinfo form "http://@host"), any '?' or '#' in the
# raw URL (including a bare '?' or '#'), or a non-root path, so the
# script never builds a request against an ambiguous URL.
LOOPBACK_OK="$(BACKEND_BASE="$BACKEND_BASE" python3 - <<'PY'
import ipaddress
import os
import sys
import urllib.parse

raw = os.environ.get("BACKEND_BASE", "").strip()
if not raw:
    print("REJECT: VANCINE_BACKEND_BASE is empty", file=sys.stderr)
    sys.exit(0)
try:
    parsed = urllib.parse.urlparse(raw)
except ValueError as e:
    print(f"REJECT: cannot parse URL: {e}", file=sys.stderr)
    sys.exit(0)
scheme = parsed.scheme
if scheme not in ("http", "https"):
    print(
        f"REJECT: scheme {scheme!r} is not http or https",
        file=sys.stderr,
    )
    sys.exit(0)
if "@" in parsed.netloc:
    print("REJECT: URL must not carry userinfo", file=sys.stderr)
    sys.exit(0)
if "?" in raw:
    print("REJECT: URL must not carry a query string", file=sys.stderr)
    sys.exit(0)
if "#" in raw:
    print("REJECT: URL must not carry a fragment", file=sys.stderr)
    sys.exit(0)
if parsed.path not in ("", "/"):
    print(
        f"REJECT: URL path must be empty or '/', got {parsed.path!r}",
        file=sys.stderr,
    )
    sys.exit(0)
host = (parsed.hostname or "").strip()
if not host:
    print("REJECT: URL has no host", file=sys.stderr)
    sys.exit(0)
if host.lower() == "localhost":
    print("ACCEPT")
    sys.exit(0)
try:
    candidate = ipaddress.ip_address(host)
except ValueError as e:
    print(
        f"REJECT: {host!r} is neither 'localhost' nor an IP literal ({e})",
        file=sys.stderr,
    )
    sys.exit(0)
if not candidate.is_loopback:
    print(
        f"REJECT: {host!r} parses to {candidate}, which is not a loopback address",
        file=sys.stderr,
    )
    sys.exit(0)
print("ACCEPT")
PY
)"
if [[ "$LOOPBACK_OK" != "ACCEPT" ]]; then
  echo "error: $BACKEND_BASE is not an acceptable loopback target" >&2
  echo "       this script is for local SQLite verification only" >&2
  echo "       the script unconditionally rejects non-loopback targets" >&2
  exit 67
fi

if [[ ! -f "$SEED_FILE" ]]; then
  echo "Seed file not found: $SEED_FILE" >&2
  exit 1
fi

# Login: pipe the password into Python's stdin, Python assembles the
# login JSON and writes it to its stdout, curl reads the body from
# stdin via `--data-binary @-`. The password, the JSON body, and the
# URL stay out of every command arg, every temp file, and the shell
# history. The Authorization-header isn't required for login.
echo "Logging into ${BACKEND_BASE} as ${ROOT_USER}…"
LOGIN_RESPONSE="$(
  printf '%s' "$VANCINE_ROOT_PASSWORD" \
    | ROOT_USER="$ROOT_USER" python3 -c '
import json
import os
import sys
pwd = sys.stdin.read()
print(json.dumps({"username": os.environ["ROOT_USER"], "password": pwd}, ensure_ascii=False))
' \
    | curl --noproxy '*' -fsS -X POST "${BACKEND_BASE}/api/user/login" \
        -H 'Content-Type: application/json' \
        --data-binary @-
)" || {
  echo "Failed to POST ${BACKEND_BASE}/api/user/login" >&2
  exit 1
}

# Extract the access token from the login response. The token is
# captured in a bash variable for one-shot use by the subsequent PUT
# request — it is never written to a file and never appears on any
# command line below (the curl config is built by an ephemeral
# <(printf ...) process substitution).
ACCESS_TOKEN="$(printf '%s' "$LOGIN_RESPONSE" \
  | python3 -c 'import sys, json; print(json.load(sys.stdin)["data"]["access_token"])')" || {
  echo "Failed to parse access token from ${BACKEND_BASE}/api/user/login response" >&2
  exit 1
}

if [[ -z "$ACCESS_TOKEN" ]]; then
  echo "Failed to obtain access token from ${BACKEND_BASE}/api/user/login" >&2
  exit 1
fi

# PUT: pipe the option JSON from Python's stdout to curl's stdin via
# `--data-binary @-`. The Authorization header (which carries the
# access token) is built by a short-lived `<(printf ...)` process
# substitution — the token is never on the curl command line.
echo "PUT /api/option (key=About)…"
PUT_RAW="$(
  python3 - "$SEED_FILE" <<'PY' | curl --noproxy '*' -fsS \
      -K <(printf 'request = "PUT"\nurl = "%s/api/option/"\nheader = "Authorization: Bearer %s"\nheader = "Content-Type: application/json"\n' \
          "$BACKEND_BASE" "$ACCESS_TOKEN") \
      --data-binary @-
import json
import sys
with open(sys.argv[1], "r", encoding="utf-8") as f:
    seed = json.load(f)
value = json.dumps(seed, ensure_ascii=False)
print(json.dumps({"key": "About", "value": value}, ensure_ascii=False))
PY
)" || {
  echo "Failed to PUT ${BACKEND_BASE}/api/option (key=About)" >&2
  exit 1
}
echo "$PUT_RAW"

# Verify the PUT response is well-formed JSON and that the success
# field is exactly true. A 200 with success !== true is treated as a
# failed seed.
PUT_OK="$(PUT_RAW="$PUT_RAW" python3 - <<'PY'
import json
import os
import sys
raw = os.environ.get("PUT_RAW", "")
if not raw.strip():
    print("REJECT: empty body", file=sys.stderr)
    sys.exit(0)
try:
    payload = json.loads(raw)
except json.JSONDecodeError as e:
    print(f"REJECT: not valid JSON: {e}", file=sys.stderr)
    sys.exit(0)
if not isinstance(payload, dict):
    print("REJECT: top-level value is not an object", file=sys.stderr)
    sys.exit(0)
if payload.get("success") is not True:
    print(f"REJECT: success !== true: {payload}", file=sys.stderr)
    sys.exit(0)
print("ACCEPT")
PY
)"
if [[ "$PUT_OK" != "ACCEPT" ]]; then
  echo "error: PUT /api/option (key=About) did not return success=true" >&2
  exit 1
fi

# Verify the seed by re-reading /api/about on the same loopback target
# with both Accept-Language: en and Accept-Language: zh-CN. Each GET
# is issued exactly once. The resulting data fields are compared
# character-for-character with the corresponding keys in seeds.json.
# The zh-CN readback body is then reused for the final sample — no
# second GET is issued.
echo "GET /api/about (verify, Accept-Language: en)…"
ABOUT_EN_RAW="$(curl --noproxy '*' -fsS -H 'Accept-Language: en' "${BACKEND_BASE}/api/about")" || {
  echo "Failed to GET ${BACKEND_BASE}/api/about (en)" >&2
  exit 1
}
echo "GET /api/about (verify, Accept-Language: zh-CN)…"
ABOUT_ZH_RAW="$(curl --noproxy '*' -fsS -H 'Accept-Language: zh-CN' "${BACKEND_BASE}/api/about")" || {
  echo "Failed to GET ${BACKEND_BASE}/api/about (zh-CN)" >&2
  exit 1
}

SEED_OK="$(SEED_FILE="$SEED_FILE" ABOUT_EN_RAW="$ABOUT_EN_RAW" ABOUT_ZH_RAW="$ABOUT_ZH_RAW" python3 - <<'PY'
import json
import os
import sys

seed_path = os.environ["SEED_FILE"]
with open(seed_path, "r", encoding="utf-8") as f:
    seed = json.load(f)
expected_en = seed.get("en")
expected_zh = seed.get("zh-CN")
if not isinstance(expected_en, str) or not isinstance(expected_zh, str):
    print("REJECT: seeds.json must contain string 'en' and 'zh-CN' keys", file=sys.stderr)
    sys.exit(0)

def parse(raw):
    if not raw.strip():
        print(f"REJECT: empty body", file=sys.stderr)
        sys.exit(0)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"REJECT: not valid JSON: {e}", file=sys.stderr)
        sys.exit(0)
    if not isinstance(payload, dict):
        print("REJECT: top-level value is not an object", file=sys.stderr)
        sys.exit(0)
    if payload.get("success") is not True:
        print(f"REJECT: success !== true: {payload}", file=sys.stderr)
        sys.exit(0)
    data = payload.get("data")
    if not isinstance(data, str):
        print("REJECT: data field is not a string", file=sys.stderr)
        sys.exit(0)
    return data

got_en = parse(os.environ["ABOUT_EN_RAW"])
got_zh = parse(os.environ["ABOUT_ZH_RAW"])

if got_en != expected_en:
    print(
        f"REJECT: en readback does not match seeds.json (got {len(got_en)} chars, expected {len(expected_en)})",
        file=sys.stderr,
    )
    sys.exit(0)
if got_zh != expected_zh:
    print(
        f"REJECT: zh-CN readback does not match seeds.json (got {len(got_zh)} chars, expected {len(expected_zh)})",
        file=sys.stderr,
    )
    sys.exit(0)
print("ACCEPT")
PY
)"
if [[ "$SEED_OK" != "ACCEPT" ]]; then
  echo "error: GET /api/about readback did not match seeds.json" >&2
  echo "       the PUT may have succeeded but the readback is not usable" >&2
  exit 1
fi

# Reuse the already-verified zh-CN body for the final sample. No
# second GET is issued — the verified readback is the source of truth.
echo "About content seeded and verified. Sample of GET /api/about (zh-CN):"
ABOUT_ZH_DATA="$(printf '%s' "$ABOUT_ZH_RAW" \
  | python3 -c 'import json,sys; print(json.load(sys.stdin).get("data",""))')"
SAMPLE="$(printf '%s' "$ABOUT_ZH_DATA" \
  | python3 -c 'import sys; d=sys.stdin.read(); print(d[:280] + ("\u2026" if len(d) > 280 else ""))')"
printf '%s\n' "$SAMPLE"
