package controller

// CP3 P1-E01-E08 Unified real HTTP relay smoke.
//
// One integration test file. The router uses the same key order as
// production: TokenAuth -> ModelRequestRateLimit -> Distribute -> Relay,
// built inside the controller package (no import cycle). The database is
// initialized through the real model.InitDB / model.InitLogDB chain, so
// reserved-word columns are set and channel selection / billing run against
// a real schema. The local OpenAI-compatible httptest server uses a
// high-distinctiveness sentinel credential that MUST never leak.
//
// Handler discipline: the upstream mock and any relay goroutine record
// outcomes via sync.Mutex / atomic counters and ordinary errors only. The
// main goroutine asserts after the client response has been observed and any
// refund barrier has fired.

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/i18n"
	"github.com/QuantumNous/new-api/middleware"
	"github.com/QuantumNous/new-api/model"
	"github.com/QuantumNous/new-api/relaykit/types"
	"github.com/QuantumNous/new-api/setting"
	"github.com/QuantumNous/new-api/setting/ratio_setting"
	"github.com/alicebob/miniredis/v2"
	"github.com/gin-gonic/gin"
	"github.com/go-redis/redis/v8"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// relaySmokeUpstreamKey is the high-distinctiveness sentinel credential the
// smoke upstream uses. It MUST NOT look like a real provider key and MUST
// differ from every client token created in the same test.
const relaySmokeUpstreamKey = "smoke-upstream-sentinel-DO-NOT-USE-9f3b2e"

// relaySmokeModel is the model name used in the smoke harness.
const relaySmokeModel = "smoke-model"

// Fixed fixture inputs (external contract, not copied production helpers).
const (
	relaySmokeStartQuota     = 100000
	relaySmokeTokenQuota     = 100000
	relaySmokePromptTokens   = 7
	relaySmokeCompTokens     = 3
	relaySmokeExpectedCost   = 25 // 10 total tokens * 2.5
	relaySmokeFinalUserQuota = 100000 - relaySmokeExpectedCost
)

// relayRedisMode controls which Redis client setupRelaySmoke uses.
type relayRedisMode int

const (
	// relayRedisPerTest creates a per-test miniredis + client + tracker.
	// The client is closed in test cleanup.
	relayRedisPerTest relayRedisMode = iota
	// relayRedisSharedRateLimiter uses the shared p10SharedRedisClient and
	// p10SharedTracker. The shared client is NOT closed in test cleanup;
	// TestMain closes it. This mode exists because limiter.New's sync.Once
	// permanently saves the first *redis.Client it receives.
	relayRedisSharedRateLimiter
)

// relaySmokeFixture groups the upstream, the router, the client token key,
// and counters so each subtest exercises one boundary in isolation.
var (
	smokeSeqMu sync.Mutex
	smokeSeq   int
)

type relaySmokeFixture struct {
	router      *gin.Engine
	upstream    *httptest.Server
	upstreamCh  chan struct{} // each upstream request sends here
	upstreamHit atomic.Int64
	tracker     *p10RedisTracker

	userID    int
	tokenID   int
	tokenKey  string
	channelID int

	mu             sync.Mutex
	lastAuthHeader string
	mockErr        error
}

// smokeFixtureKey is the request-context key the upstream mock uses to find
// the fixture.
type smokeFixtureKey struct{}

// chatBody returns a minimal valid chat completion body the relay stack will
// accept, marshaled with common.Marshal. Returns nil on error so the caller
// can require.NoError in the main goroutine.
func chatBody(t *testing.T, stream bool) []byte {
	t.Helper()
	body := map[string]interface{}{
		"model":    relaySmokeModel,
		"messages": []map[string]string{{"role": "user", "content": "ping"}},
		"stream":   stream,
	}
	b, err := common.Marshal(body)
	require.NoError(t, err, "chatBody marshal must succeed")
	return b
}

// relayUpstreamUsage is the fixed upstream usage reported in the success body.
const relayUpstreamUsage = `"usage":{"prompt_tokens":7,"completion_tokens":3,"total_tokens":10}`

// successBody returns the fixed success response bytes. Pre-generated by the
// main goroutine; the mock only writes it.
func successBody() []byte {
	return []byte(`{
		"id":"chatcmpl-smoke",
		"object":"chat.completion",
		"created":1700000000,
		"model":"smoke-model",
		"choices":[{
			"index":0,
			"message":{"role":"assistant","content":"hello"},
			"finish_reason":"stop"
		}],
		` + relayUpstreamUsage + `
	}`)
}

// setupRelaySmoke stands up an isolated DB through the real production init
// chain, seeds one user + token + one OpenAI-compatible channel + ability
// pointing at the local upstream, and exposes a real router through
// TokenAuth -> ModelRequestRateLimit -> Distribute -> Relay. The token is
// finite-quota (UnlimitedQuota=false) so pre-consume / settle / refund token
// state is precisely observable.
func setupRelaySmoke(t *testing.T, dbType common.DatabaseType, redisMode relayRedisMode) *relaySmokeFixture {
	t.Helper()
	require.NoError(t, i18n.Init())
	p10SetupDatabase(t, dbType,
		&model.User{}, &model.Token{}, &model.Channel{}, &model.Log{},
		&model.Ability{}, &model.Model{}, &model.UserSession{},
		&model.UserSubscription{}, &model.SubscriptionOrder{}, &model.SubscriptionPreConsumeRecord{},
		&model.Option{}, &model.Redemption{}, &model.QuotaData{},
	)

	// Use miniredis to provide a real in-process Redis instance. The
	// telemetry goroutine's Redis calls go to miniredis (safe, in-memory),
	// and the cleanup restores the previous Redis globals after the miniredis
	// client is closed. This eliminates the cross-test write-vs-read race
	// that occurred when RedisEnabled was set false and never restored.
	// The p10RedisTracker hook records all Redis commands with sanitized
	// category classification so tests can wait for specific async task
	// types (token-cache, rate-limit, performance) without exposing sensitive keys.
	//
	// For E07 (rate limiter), the shared p10SharedRedisClient is used because
	// the limiter.New singleton (sync.Once) permanently saves the first client
	// it receives. The shared client lives for the entire process and is only
	// closed in TestMain. For all other tests, a per-test miniredis is created.
	prevRedisEnabled := common.RedisEnabled
	prevRDB := common.RDB
	var redisClient *redis.Client
	var tracker *p10RedisTracker
	sharedRedis := redisMode == relayRedisSharedRateLimiter
	if sharedRedis {
		// E07 mode: use the shared client and shared tracker. The shared
		// client's single permanent hook is the shared tracker. No per-test
		// hook accumulation.
		redisClient = p10SharedRedisClient
		tracker = p10SharedTracker
	} else {
		// Default mode: per-test miniredis with per-test tracker.
		redisServer := miniredis.RunT(t)
		redisClient = redis.NewClient(&redis.Options{Addr: redisServer.Addr()})
		require.NoError(t, redisClient.Ping(context.Background()).Err())
		tracker = newP10RedisTracker()
		redisClient.AddHook(tracker)
	}
	require.NoError(t, redisClient.Ping(context.Background()).Err())
	common.RedisEnabled = true
	common.RDB = redisClient
	t.Cleanup(func() {
		// Restore globals FIRST, then close the per-test client. This
		// ensures no goroutine reads common.RDB after the client is closed.
		common.RedisEnabled = prevRedisEnabled
		common.RDB = prevRDB
		// Only close per-test clients. The shared client is closed in TestMain.
		if !sharedRedis {
			assert.NoError(t, redisClient.Close(), "redis client close must succeed")
		}
	})

	prevMemoryCache := common.MemoryCacheEnabled
	common.MemoryCacheEnabled = false
	t.Cleanup(func() { common.MemoryCacheEnabled = prevMemoryCache })

	prevGroupRatio := common.TopupGroupRatio2JSONString()
	require.NoError(t, common.UpdateTopupGroupRatioByJSONString(`{"default":1}`))
	t.Cleanup(func() {
		if err := common.UpdateTopupGroupRatioByJSONString(prevGroupRatio); err != nil {
			t.Errorf("restore group ratio: %v", err)
		}
	})

	prevModelRatio := ratio_setting.GetModelRatioCopy()
	require.NoError(t, ratio_setting.UpdateModelRatioByJSONString(
		`{"`+relaySmokeModel+`": 2.5}`))
	t.Cleanup(func() {
		if b, err := common.Marshal(prevModelRatio); err == nil {
			if err := ratio_setting.UpdateModelRatioByJSONString(string(b)); err != nil {
				t.Errorf("restore model ratio: %v", err)
			}
		}
	})

	prevStreamingTimeout := constant.StreamingTimeout
	constant.StreamingTimeout = 300
	t.Cleanup(func() { constant.StreamingTimeout = prevStreamingTimeout })

	// common.Init() is not called in tests, so common.SyncFrequency defaults
	// to 0. Billing cache writes (cacheIncrUserQuota / cacheIncrTokenQuota)
	// check the cache key's TTL > 0 before calling HINCRBY. If SyncFrequency
	// is 0, the auth-path cache write (cacheSetToken / cacheSetUser) sets no
	// TTL, so the billing HINCRBY is silently skipped. Setting SyncFrequency
	// to 60 (the production default) ensures cache keys get a TTL and billing
	// writes actually reach Redis.
	prevSyncFrequency := common.SyncFrequency
	common.SyncFrequency = 60
	t.Cleanup(func() { common.SyncFrequency = prevSyncFrequency })

	// Use a deterministic atomic counter for IDs so SQLite and PG fixtures
	// produce the same IDs (no time.Now() dependency).
	smokeSeqMu.Lock()
	smokeSeq++
	userID := smokeSeq*1000 + 1
	channelID := smokeSeq*1000 + 2
	tokenID := smokeSeq*1000 + 3
	smokeSeqMu.Unlock()
	// TokenAuth extracts the key as the part before the first "-". Use a bare
	// alphanumeric key with no dash so parts[0] equals the full token key.
	tokenKey := common.GetRandomString(32)

	user := &model.User{
		Id:          userID,
		Username:    fmt.Sprintf("smoke-%d", userID),
		Password:    "ignored",
		Role:        common.RoleCommonUser,
		Status:      common.UserStatusEnabled,
		Group:       "default",
		AffCode:     fmt.Sprintf("smoke-%d", userID),
		AuthVersion: 1,
		Quota:       relaySmokeStartQuota,
	}
	require.NoError(t, model.DB.Create(user).Error)

	token := &model.Token{
		Id:             tokenID,
		UserId:         userID,
		Key:            tokenKey,
		Name:           "smoke-token",
		Status:         common.TokenStatusEnabled,
		ExpiredTime:    -1, // never expires
		RemainQuota:    relaySmokeTokenQuota,
		UnlimitedQuota: false,
		Group:          "default",
		CreatedTime:    time.Now().Unix(),
		AccessedTime:   time.Now().Unix(),
	}
	require.NoError(t, model.DB.Create(token).Error)
	priority := int64(1)
	emptyStr := ""
	channel := &model.Channel{
		Id:       channelID,
		Name:     "smoke-channel",
		Type:     constant.ChannelTypeOpenAI,
		Status:   common.ChannelStatusEnabled,
		Key:      relaySmokeUpstreamKey,
		BaseURL:  &emptyStr, // patched in after upstream URL is known
		Group:    "default",
		Priority: &priority,
	}
	require.NoError(t, model.DB.Create(channel).Error)

	ability := &model.Ability{
		Group:     "default",
		Model:     relaySmokeModel,
		ChannelId: channelID,
		Enabled:   true,
		Priority:  &priority,
		Weight:    10,
	}
	require.NoError(t, model.DB.Create(ability).Error)

	upstreamCh := make(chan struct{}, 1024)
	f := &relaySmokeFixture{
		upstreamCh: upstreamCh,
		tracker:    tracker,
		userID:     userID,
		tokenID:    tokenID,
		tokenKey:   tokenKey,
		channelID:  channelID,
	}

	// The upstream mock only records a hit, the auth header, and any read or
	// write error into the fixture; it never touches testing.T.
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		f.upstreamHit.Add(1)
		select {
		case f.upstreamCh <- struct{}{}:
		default:
		}
		f.mu.Lock()
		f.lastAuthHeader = r.Header.Get("Authorization")
		f.mu.Unlock()
		body, err := io.ReadAll(r.Body)
		if err != nil {
			f.mu.Lock()
			f.mockErr = err
			f.mu.Unlock()
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		_ = body
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("x-request-id", "smoke-upstream")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write(successBody()); err != nil {
			f.mu.Lock()
			f.mockErr = err
			f.mu.Unlock()
		}
	}))
	f.upstream = upstream
	t.Cleanup(upstream.Close)

	require.NoError(t, model.DB.Model(&model.Channel{}).
		Where("id = ?", channelID).
		Update("base_url", upstream.URL+"/v1").Error)

	f.router = gin.New()
	relayGroup := f.router.Group("/v1")
	relayGroup.Use(middleware.TokenAuth())
	relayGroup.Use(middleware.ModelRequestRateLimit())
	relayGroup.Use(middleware.Distribute())
	relayGroup.POST("/chat/completions", func(c *gin.Context) {
		ctx := context.WithValue(c.Request.Context(), smokeFixtureKey{}, f)
		c.Request = c.Request.WithContext(ctx)
		Relay(c, types.RelayFormatOpenAI)
	})

	return f
}

// doRequest fires a real POST through the relay router.
func doRequest(f *relaySmokeFixture, key string, body []byte) *httptest.ResponseRecorder {
	req := httptest.NewRequest(http.MethodPost, "/v1/chat/completions", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	if key != "" {
		req.Header.Set("Authorization", "Bearer "+key)
	}
	rec := httptest.NewRecorder()
	f.router.ServeHTTP(rec, req)
	return rec
}

// waitUpstreamHit waits for the upstream to observe n hits, using a timeout
// guard rather than a fixed sleep.
func waitUpstreamHit(ch <-chan struct{}, n int) bool {
	for i := 0; i < n; i++ {
		select {
		case <-ch:
		case <-time.After(5 * time.Second):
			return false
		}
	}
	return true
}

// readUserQuota returns the persisted user quota.
func readUserQuota(t *testing.T, userID int) int {
	t.Helper()
	var quota int
	require.NoError(t, model.DB.Model(&model.User{}).
		Where("id = ?", userID).Select("quota").Scan(&quota).Error)
	return quota
}

// readTokenQuota returns the persisted token remain and used quota.
func readTokenQuota(t *testing.T, userID int) (remain int, used int) {
	t.Helper()
	var remainQ, usedQ int
	require.NoError(t, model.DB.Model(&model.Token{}).
		Where("user_id = ?", userID).Select("remain_quota").Scan(&remainQ).Error)
	require.NoError(t, model.DB.Model(&model.Token{}).
		Where("user_id = ?", userID).Select("used_quota").Scan(&usedQ).Error)
	return remainQ, usedQ
}

// countUserLogs counts consume logs for a user.
func countUserLogs(t *testing.T, userID int) int64 {
	t.Helper()
	var n int64
	require.NoError(t, model.DB.Model(&model.Log{}).
		Where("user_id = ?", userID).Count(&n).Error)
	return n
}

// refundBarrier provides a deterministic wait for the asynchronous
// BillingSession.Refund writes (user quota restore + token quota restore)
// so the test never tears down the DB while the gopool goroutine is still
// writing. It uses GORM after-update callbacks on the users and tokens
// tables; the callback only sends to a buffered channel and never touches
// testing.T. The barrier verifies persistent state after each event rather
// than draining-then-assuming: each DB-update event triggers a re-read of
// user quota, token remain, and token used; the barrier succeeds only when
// ALL three match the expected final values. A timeout is a failure guard,
// not a success criterion.
type refundBarrier struct {
	userSig    chan struct{}
	tokenSig   chan struct{}
	expectQ    int // expected final user quota
	expectRem  int // expected final token remain
	expectUsed int // expected final token used
	userID     int
}

const (
	refundBarrierUserCallback  = "test:refund_barrier_user_v2"
	refundBarrierTokenCallback = "test:refund_barrier_token_v2"
)

// installRefundBarrier registers unique after-update callbacks on the users
// and tokens tables, scoped to the given user ID. The barrier succeeds
// only when the persisted user quota, token remain, and token used all
// match the expected final values.
func installRefundBarrier(t *testing.T, userID, expectQ, expectRem, expectUsed int) *refundBarrier {
	t.Helper()
	b := &refundBarrier{
		userSig:    make(chan struct{}, 16),
		tokenSig:   make(chan struct{}, 16),
		expectQ:    expectQ,
		expectRem:  expectRem,
		expectUsed: expectUsed,
		userID:     userID,
	}
	require.NoError(t, model.DB.Callback().Update().After("gorm:update").
		Register(refundBarrierUserCallback, func(tx *gorm.DB) {
			if tx.Statement.Table == "users" {
				select {
				case b.userSig <- struct{}{}:
				default:
				}
			}
		}))
	require.NoError(t, model.DB.Callback().Update().After("gorm:update").
		Register(refundBarrierTokenCallback, func(tx *gorm.DB) {
			if tx.Statement.Table == "tokens" {
				select {
				case b.tokenSig <- struct{}{}:
				default:
				}
			}
		}))
	t.Cleanup(func() {
		assert.NoError(t, model.DB.Callback().Update().Remove(refundBarrierUserCallback),
			"refund barrier user callback cleanup must succeed")
		assert.NoError(t, model.DB.Callback().Update().Remove(refundBarrierTokenCallback),
			"refund barrier token callback cleanup must succeed")
	})
	return b
}

// waitForRefund consumes DB-update events and checks persistent state after
// each one. It returns when the persisted user quota, token remain, and token
// used all match the expected final values. The timeout is a failure guard,
// not a success criterion: if the refund has already completed before
// waitForRefund is called, the channel buffer still contains the event(s)
// and the state check succeeds on the first read.
func (b *refundBarrier) waitForRefund(t *testing.T) {
	t.Helper()
	deadline := time.After(5 * time.Second)
	for {
		select {
		case <-b.userSig:
			if b.checkState(t) {
				return
			}
		case <-b.tokenSig:
			if b.checkState(t) {
				return
			}
		case <-deadline:
			// Timeout unconditionally fails: the refund's DB-update signal
			// must have been observed. A final state re-read that happens
			// to match does NOT count as success — only a real user/token
			// update signal that persists to the expected final values
			// proves the refund completed.
			require.Fail(t, "refund barrier: persistent state did not reach expected values within 5s (no update signal observed)")
		}
	}
}

// checkState reads the persisted user quota, token remain, and token used
// and returns true only when all three match the expected final values.
func (b *refundBarrier) checkState(t *testing.T) bool {
	t.Helper()
	var q int
	if err := model.DB.Model(&model.User{}).Where("id = ?", b.userID).Select("quota").Scan(&q).Error; err != nil {
		return false
	}
	var rem, used int
	if err := model.DB.Model(&model.Token{}).Where("user_id = ?", b.userID).Select("remain_quota").Scan(&rem).Error; err != nil {
		return false
	}
	if err := model.DB.Model(&model.Token{}).Where("user_id = ?", b.userID).Select("used_quota").Scan(&used).Error; err != nil {
		return false
	}
	return q == b.expectQ && rem == b.expectRem && used == b.expectUsed
}

// assertNoUpstreamKeyLeak checks that the sentinel never appears in a body,
// any header value, or a persisted log.
func assertNoUpstreamKeyLeak(t *testing.T, body string, header http.Header, logs []model.Log) {
	t.Helper()
	assert.NotContains(t, body, relaySmokeUpstreamKey, "response body leaks upstream key")
	for k, vs := range header {
		for _, v := range vs {
			assert.NotContains(t, v, relaySmokeUpstreamKey, "header %q leaks upstream key", k)
		}
	}
	for _, l := range logs {
		assert.NotContains(t, l.Content, relaySmokeUpstreamKey, "log content leaks upstream key")
		assert.NotContains(t, l.Other, relaySmokeUpstreamKey, "log other leaks upstream key")
	}
}

// awaitRelayAsync is a stable business-concept helper: it captures a
// tracker checkpoint before a relay request, then after the request
// completes (and any worker has joined), waits for the expected async
// Redis events and asserts no non-redis.Nil errors occurred after the
// checkpoint. Only WRITE categories satisfy settlement/refund/telemetry
// waits; read categories are used for auth-path queries. Common patterns:
//   - successful relay: token-write, user-write, perf-write
//   - failed relay (refund): token-write, user-write, perf-write
//   - rate-limit first request: rate-limit, token-write, user-write, perf-write
//   - rate-limit second request: rate-limit (only)
//   - E03 rejection: (empty — no billing events expected)
//
// snapshotAfter returns a one-shot snapshot of events after the given
// checkpoint. It does not use a timer, sleep, or polling — it is an
// instantaneous read of the current ledger state.
func snapshotAfter(f *relaySmokeFixture, ckpt int64) []p10RedisEvent {
	f.tracker.mu.Lock()
	defer f.tracker.mu.Unlock()
	var matched []p10RedisEvent
	for _, evt := range f.tracker.events {
		if evt.Seq > ckpt {
			matched = append(matched, evt)
		}
	}
	return matched
}

// assertNoBillingWrites asserts that the given snapshot contains no
// billing/quota mutation events (token-quota-write, user-quota-write,
// perf-write). Auth-cache writes (token-cache-write, user-cache-write)
// are allowed — they are synchronous auth-path cache updates, not billing.
func assertNoBillingWrites(t *testing.T, snapshot []p10RedisEvent) {
	t.Helper()
	for _, evt := range snapshot {
		for _, bc := range p10BillingQuotaCategories {
			if evt.Category == bc {
				t.Errorf("no billing mutation expected after checkpoint, got category=%q cmd=%q", evt.Category, evt.Cmd)
			}
		}
	}
}

// awaitRelayAsync is a stable business-concept helper: it captures a
// tracker checkpoint before a relay request, then after the request
// completes (and any worker has joined), waits for the expected async
// Redis events and asserts no non-redis.Nil errors occurred after the
// checkpoint. Only WRITE categories satisfy settlement/refund/telemetry
// waits. When reqs is nil/empty the caller should use snapshotAfter +
// assertNoBillingWrites instead.
func awaitRelayAsync(t *testing.T, f *relaySmokeFixture, ckpt int64, reqs []p10WaitRequirement) {
	t.Helper()
	require.NotEmpty(t, reqs, "use snapshotAfter + assertNoBillingWrites for no-event assertions")
	result := f.tracker.waitAfter(ckpt, reqs, 5*time.Second)
	require.False(t, result.TimedOut,
		"async events not observed within 5s: wanted %v, got %d matched", reqs, len(result.Matched))
	require.Empty(t, result.Errors,
		"no non-redis.Nil errors expected after checkpoint, got %v", result.Errors)
}

// --- E01 non-stream success ---

func TestRelaySmokeE01_NonStreamSuccess(t *testing.T) {
	p10RunAcrossDatabases(t, "E01", e01NonStreamBody)
}

func e01NonStreamBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)
	ckpt := f.tracker.checkpoint()
	rec := doRequest(f, f.tokenKey, chatBody(t, false))
	require.True(t, waitUpstreamHit(f.upstreamCh, 1), "upstream must be hit exactly once")

	require.Equal(t, http.StatusOK, rec.Code, "non-stream success must be 200, body=%s", rec.Body.String())
	require.Equal(t, int64(1), f.upstreamHit.Load(), "upstream must be hit exactly once")
	body := rec.Body.String()
	assert.Contains(t, body, "chatcmpl-smoke")
	assertNoUpstreamKeyLeak(t, body, rec.Header(), nil)

	f.mu.Lock()
	mockErr := f.mockErr
	f.mu.Unlock()
	require.NoError(t, mockErr, "upstream mock must not have recorded an error")

	awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})
}

// --- E02 SSE stream success ---

func TestRelaySmokeE02_StreamSuccessSingleUpstreamHit(t *testing.T) {
	p10RunAcrossDatabases(t, "E02", e02StreamBody)
}

func e02StreamBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)
	ckpt := f.tracker.checkpoint()

	// Swap the upstream to an SSE emitter; the old server is already closed
	// via its registered cleanup, and the new one gets its own cleanup.
	f.upstream.Close()
	streamCh := make(chan struct{}, 8)
	streamBody := strings.Join([]string{
		`data: {"id":"chatcmpl-stream","object":"chat.completion.chunk","created":1,"model":"smoke-model","choices":[{"index":0,"delta":{"role":"assistant"}}]}`,
		``,
		`data: {"id":"chatcmpl-stream","object":"chat.completion.chunk","created":1,"model":"smoke-model","choices":[{"index":0,"delta":{"content":"hi"},"finish_reason":"stop"}]}`,
		``,
		`data: [DONE]`,
		``,
	}, "\n")
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		f.upstreamHit.Add(1)
		select {
		case streamCh <- struct{}{}:
		default:
		}
		w.Header().Set("Content-Type", "text/event-stream")
		w.Header().Set("Cache-Control", "no-cache")
		w.WriteHeader(http.StatusOK)
		if _, err := io.WriteString(w, streamBody); err != nil {
			f.mu.Lock()
			f.mockErr = err
			f.mu.Unlock()
		}
	}))
	f.upstream = srv
	t.Cleanup(srv.Close)
	require.NoError(t, model.DB.Model(&model.Channel{}).
		Where("id = ?", f.channelID).
		Update("base_url", srv.URL+"/v1").Error)

	rec := doRequest(f, f.tokenKey, chatBody(t, true))
	require.True(t, waitUpstreamHit(streamCh, 1), "upstream stream must be hit exactly once")
	require.Equal(t, int64(1), f.upstreamHit.Load(), "upstream must be hit exactly once (no extra request)")

	require.Less(t, rec.Code, http.StatusInternalServerError, "stream response must not be a server error")
	body := rec.Body.String()
	assert.Contains(t, body, "chatcmpl-stream", "body must include the SSE chunk id")
	assert.Contains(t, body, "[DONE]", "body must include the SSE [DONE] terminator")

	f.mu.Lock()
	mockErr := f.mockErr
	f.mu.Unlock()
	require.NoError(t, mockErr, "upstream mock must not have recorded an error")

	awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})
}

// --- E03 missing / invalid / disabled token, no state change ---

func TestRelaySmokeE03_TokenRejectionBlocksUpstream(t *testing.T) {
	p10RunAcrossDatabases(t, "E03", e03TokenRejectionBody)
}

func e03TokenRejectionBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)

	// Record the persistent state snapshot BEFORE the first request so
	// the "unchanged" assertions are against a clean baseline.
	userQuotaBefore := readUserQuota(t, f.userID)
	tokenRemainBefore, tokenUsedBefore := readTokenQuota(t, f.userID)
	logsBefore := countUserLogs(t, f.userID)
	hitsBefore := f.upstreamHit.Load()

	requestBody := chatBody(t, false)

	// Missing and invalid token requests never reach the relay handler,
	// so no auth-cache writes occur.
	cases := []struct {
		name string
		key  string
	}{
		{name: "missing token", key: ""},
		{name: "invalid token", key: "definitely-not-a-real-key"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ckpt := f.tracker.checkpoint()
			rec := doRequest(f, tc.key, requestBody)
			require.True(t, rec.Code == http.StatusUnauthorized || rec.Code == http.StatusForbidden,
				"must be 401/403, got %d", rec.Code)
			assert.Equal(t, hitsBefore, f.upstreamHit.Load(), "upstream hit delta must be 0")
			assert.Equal(t, userQuotaBefore, readUserQuota(t, f.userID), "user quota unchanged")
			remain, used := readTokenQuota(t, f.userID)
			assert.Equal(t, tokenRemainBefore, remain, "token remain unchanged")
			assert.Equal(t, tokenUsedBefore, used, "token used unchanged")
			assert.Equal(t, logsBefore, countUserLogs(t, f.userID), "consume log count unchanged")
			snap := snapshotAfter(f, ckpt)
			assertNoBillingWrites(t, snap)
		})
	}

	// Disabled token: disable the token in the DB directly (not via a shared
	// token struct, which races with gopool goroutines from the pre-warm
	// path). Then make the request and assert rejection. The auth-path
	// cache write (from GetTokenByKey during the rejected request) is a
	// synchronous read followed by a cache-set, NOT a settlement event.
	t.Run("disabled token", func(t *testing.T) {
		// Direct DB update avoids sharing a token struct with gopool
		// goroutines from GetTokenByKey/cacheSetToken.
		require.NoError(t, model.DB.Model(&model.Token{}).
			Where("user_id = ?", f.userID).
			Update("status", common.TokenStatusDisabled).Error,
			"DB update must succeed")
		t.Cleanup(func() {
			assert.NoError(t,
				model.DB.Model(&model.Token{}).
					Where("user_id = ?", f.userID).
					Update("status", common.TokenStatusEnabled).Error,
				"token restore must succeed")
		})

		// Checkpoint before the request so the auth-path cache write
		// (gopool cacheSetToken after DB read) is captured.
		ckpt := f.tracker.checkpoint()
		rec := doRequest(f, f.tokenKey, requestBody)
		require.True(t, rec.Code == http.StatusUnauthorized || rec.Code == http.StatusForbidden,
			"disabled token must be 401/403, got %d", rec.Code)
		assert.Equal(t, hitsBefore, f.upstreamHit.Load(), "upstream hit delta must be 0")
		assert.Equal(t, userQuotaBefore, readUserQuota(t, f.userID), "user quota unchanged")
		remain, used := readTokenQuota(t, f.userID)
		assert.Equal(t, tokenRemainBefore, remain, "token remain unchanged")
		assert.Equal(t, tokenUsedBefore, used, "token used unchanged")
		assert.Equal(t, logsBefore, countUserLogs(t, f.userID), "consume log count unchanged")

		// Wait for the auth-path cache write (gopool cacheSetToken) to
		// complete. This is a token-cache-write, NOT a billing mutation.
		awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
			{Category: p10RedisCatTokenCacheWrite, Count: 1},
		})

		// Snapshot and assert no billing mutations (token-quota-write,
		// user-quota-write, perf-write). Auth-cache writes are allowed.
		snap := snapshotAfter(f, ckpt)
		assertNoBillingWrites(t, snap)
	})
}

// --- E04 upstream 5xx, refund completes deterministically ---

func TestRelaySmokeE04_Upstream5xxSurfacesCleanError(t *testing.T) {
	p10RunAcrossDatabases(t, "E04", e04Upstream5xxBody)
}

func e04Upstream5xxBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)
	preCkpt := f.tracker.checkpoint()
	startUserQ := readUserQuota(t, f.userID)
	startRemain, _ := readTokenQuota(t, f.userID)

	// Swap upstream to a 5xx responder with ready/release barrier.
	f.upstream.Close()
	readyCh := make(chan struct{}, 1)
	releaseCh := make(chan struct{})
	var releaseOnce sync.Once
	var upstreamWriteErr error
	var writeErrMu sync.Mutex
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		f.upstreamHit.Add(1)
		select {
		case readyCh <- struct{}{}:
		default:
		}
		<-releaseCh
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		if _, err := w.Write([]byte(`{"error":"upstream unavailable"}`)); err != nil {
			writeErrMu.Lock()
			upstreamWriteErr = err
			writeErrMu.Unlock()
		}
	}))
	f.upstream = srv
	t.Cleanup(srv.Close)
	require.NoError(t, model.DB.Model(&model.Channel{}).
		Where("id = ?", f.channelID).
		Update("base_url", srv.URL+"/v1").Error)

	// Install refund barrier BEFORE the request goroutine starts.
	barrier := installRefundBarrier(t, f.userID, relaySmokeStartQuota, relaySmokeTokenQuota, 0)

	// Pre-generate request body in main goroutine.
	requestBody := chatBody(t, false)

	// Launch worker; register failure-safe defer immediately.
	readyOK := true
	recCh := make(chan *httptest.ResponseRecorder, 1)
	cbDone := make(chan struct{})
	go func() {
		defer close(cbDone)
		rec := doRequest(f, f.tokenKey, requestBody)
		recCh <- rec
	}()
	defer func() {
		releaseOnce.Do(func() { close(releaseCh) })
		<-cbDone
	}()

	// Wait for upstream to be reached.
	select {
	case <-readyCh:
	case <-time.After(5 * time.Second):
		readyOK = false
	}

	if !readyOK {
		require.Fail(t, "upstream handler did not signal ready within 5s")
	}

	// While upstream is blocked, read persistent state to prove pre-consume
	// happened (DB writes from DecreaseUserQuota/DecreaseTokenQuota).
	midUserQ := readUserQuota(t, f.userID)
	midTokenRemain, midTokenUsed := readTokenQuota(t, f.userID)
	userDelta := startUserQ - midUserQ
	tokenRemainDelta := startRemain - midTokenRemain
	assert.Greater(t, userDelta, 0, "user quota must decrease during pre-consume")
	assert.Equal(t, userDelta, tokenRemainDelta,
		"user quota delta (%d) must equal token remain delta (%d)", userDelta, tokenRemainDelta)
	assert.Equal(t, userDelta, midTokenUsed,
		"user quota delta (%d) must equal token used (%d)", userDelta, midTokenUsed)

	// Phase D: from pre-request checkpoint, wait for the pre-consume
	// billing goroutine to write user-quota-write and token-quota-write.
	// These are the HINCRBY calls from cacheIncrUserQuota/cacheIncrTokenQuota
	// in service/billing_session.go → model.IncreaseUserQuota/IncreaseTokenQuota.
	awaitRelayAsync(t, f, preCkpt, []p10WaitRequirement{
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
	})

	// Phase E: refund checkpoint — AFTER pre-consume writes confirmed,
	// BEFORE upstream release. This cleanly separates pre-consume writes
	// from refund writes.
	refundCkpt := f.tracker.checkpoint()

	// Phase F: release upstream and join the request worker.
	releaseOnce.Do(func() { close(releaseCh) })
	<-cbDone

	// Assert 5xx response.
	rec := <-recCh
	require.Equal(t, int64(1), f.upstreamHit.Load(), "upstream hit must be exactly 1")
	writeErrMu.Lock()
	writeErrCopy := upstreamWriteErr
	writeErrMu.Unlock()
	require.NoError(t, writeErrCopy, "upstream write error must be nil")
	require.Equal(t, http.StatusInternalServerError, rec.Code,
		"upstream 5xx must surface as 5xx, body=%s", rec.Body.String())
	body := rec.Body.String()
	assert.True(t, strings.HasPrefix(strings.TrimSpace(body), "{") || strings.Contains(body, "error"),
		"upstream 5xx body must be JSON-shaped")
	assertNoUpstreamKeyLeak(t, body, rec.Header(), nil)

	// Phase G: wait for refund barrier — persistent state must reach final values.
	barrier.waitForRefund(t)

	assert.Equal(t, relaySmokeStartQuota, readUserQuota(t, f.userID),
		"user quota must be restored to start after refund")
	remain, used := readTokenQuota(t, f.userID)
	assert.Equal(t, relaySmokeTokenQuota, remain, "token remain restored")
	assert.Equal(t, 0, used, "token used restored to 0")
	assert.Equal(t, int64(0), countUserLogs(t, f.userID), "consume log delta must be 0 on failure")

	// Phase H: from refund checkpoint, wait for the refund billing goroutine
	// to write user-quota-write, token-quota-write, and perf-write. These
	// are the refund-path HINCRBY calls (IncreaseUserQuota/IncreaseTokenQuota)
	// and the perfmetrics telemetry HINCRBY.
	awaitRelayAsync(t, f, refundCkpt, []p10WaitRequirement{
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})
}

// --- E05 quota pre-consume + settle exact ---

func TestRelaySmokeE05_QuotaPreConsumeAndSettle(t *testing.T) {
	p10RunAcrossDatabases(t, "E05", e05QuotaBody)
}

// e05Snapshot is sent by the upstream handler to the main goroutine after
// reading user/token persistent state. The handler does not call testing.T;
// it records the snapshot and any DB read error.
type e05Snapshot struct {
	userQ     int
	tokenRem  int
	tokenUsed int
	dbErr     error
	writeErr  error
}

func e05QuotaBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)
	ckpt := f.tracker.checkpoint()

	// Handler reads user/token persistent state and sends a structured
	// snapshot to the main goroutine. No testing.T in the handler.
	snapshotCh := make(chan e05Snapshot, 4)
	f.upstream.Close()
	okBody := successBody()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		f.upstreamHit.Add(1)
		var snap e05Snapshot
		snap.dbErr = model.DB.Model(&model.User{}).
			Where("id = ?", f.userID).Select("quota").Scan(&snap.userQ).Error
		if snap.dbErr == nil {
			snap.dbErr = model.DB.Model(&model.Token{}).
				Where("id = ?", f.tokenID).Select("remain_quota").Scan(&snap.tokenRem).Error
		}
		if snap.dbErr == nil {
			snap.dbErr = model.DB.Model(&model.Token{}).
				Where("id = ?", f.tokenID).Select("used_quota").Scan(&snap.tokenUsed).Error
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write(okBody); err != nil {
			snap.writeErr = err
		}
		select {
		case snapshotCh <- snap:
		default:
		}
	}))
	f.upstream = srv
	t.Cleanup(srv.Close)
	require.NoError(t, model.DB.Model(&model.Channel{}).
		Where("id = ?", f.channelID).
		Update("base_url", srv.URL+"/v1").Error)

	rec := doRequest(f, f.tokenKey, chatBody(t, false))
	require.Equal(t, http.StatusOK, rec.Code, "success must be 200, body=%s", rec.Body.String())
	require.Equal(t, int64(1), f.upstreamHit.Load(), "upstream hit must be exactly 1")

	// Read the handler's snapshot: user/token must be in pre-consume state.
	select {
	case snap := <-snapshotCh:
		require.NoError(t, snap.dbErr, "handler DB read must succeed")
		require.NoError(t, snap.writeErr, "handler write must succeed")
		assert.Less(t, snap.userQ, relaySmokeStartQuota,
			"user quota must be lower than start during pre-consume (snapshot: %d)", snap.userQ)
		assert.Less(t, snap.tokenRem, relaySmokeTokenQuota,
			"token remain must be lower than start during pre-consume (snapshot: %d)", snap.tokenRem)
		assert.Greater(t, snap.tokenUsed, 0,
			"token used must be positive during pre-consume (snapshot: %d)", snap.tokenUsed)
		// All three deltas must be consistent (same pre-consume).
		userDelta := relaySmokeStartQuota - snap.userQ
		tokenDelta := relaySmokeTokenQuota - snap.tokenRem
		assert.Equal(t, userDelta, tokenDelta,
			"user quota delta (%d) must equal token remain delta (%d)", userDelta, tokenDelta)
		assert.Equal(t, userDelta, snap.tokenUsed,
			"user quota delta (%d) must equal token used (%d)", userDelta, snap.tokenUsed)
	case <-time.After(5 * time.Second):
		require.Fail(t, "handler snapshot not received within 5s")
	}

	// After settle, final values must be exact.
	assert.Equal(t, relaySmokeFinalUserQuota, readUserQuota(t, f.userID),
		"settled user quota must be exactly %d", relaySmokeFinalUserQuota)
	remain, used := readTokenQuota(t, f.userID)
	assert.Equal(t, relaySmokeTokenQuota-relaySmokeExpectedCost, remain,
		"token remain must reflect final consumption")
	assert.Equal(t, relaySmokeExpectedCost, used, "token used must reflect final consumption")

	awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})
}

// --- E06 consume log exactly one, fields exact ---

func TestRelaySmokeE06_ConsumeLogExactlyOneWithCorrectFields(t *testing.T) {
	p10RunAcrossDatabases(t, "E06", e06ConsumeLogBody)
}

func e06ConsumeLogBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)
	ckpt := f.tracker.checkpoint()
	rec := doRequest(f, f.tokenKey, chatBody(t, false))
	require.True(t, waitUpstreamHit(f.upstreamCh, 1), "upstream must be hit")
	require.Equal(t, http.StatusOK, rec.Code, "success must be 200")

	var logs []model.Log
	require.NoError(t, model.DB.Where("user_id = ?", f.userID).Find(&logs).Error)
	require.Len(t, logs, 1, "exactly one consume log row must be written")
	l := logs[0]
	assert.Equal(t, model.LogTypeConsume, l.Type)
	assert.Equal(t, f.userID, l.UserId)
	assert.Equal(t, f.channelID, l.ChannelId, "channel id must match fixture")
	assert.Equal(t, f.tokenID, l.TokenId, "token id must match fixture")
	assert.Equal(t, relaySmokeModel, l.ModelName)
	assert.Equal(t, relaySmokePromptTokens, l.PromptTokens, "prompt tokens must be 7")
	assert.Equal(t, relaySmokeCompTokens, l.CompletionTokens, "completion tokens must be 3")
	assert.Equal(t, relaySmokeExpectedCost, l.Quota, "quota must be 25")
	assert.Equal(t, "default", l.Group)
	assert.False(t, l.IsStream, "is_stream must be false")
	assert.NotContains(t, l.Content, relaySmokeUpstreamKey)
	assert.NotContains(t, l.Other, relaySmokeUpstreamKey)

	awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})
}

// --- E07 rate-limit first allowed, second rejected ---

func TestRelaySmokeE07_RateLimitBlocksSecondRequest(t *testing.T) {
	p10RunAcrossDatabases(t, "E07", e07RateLimitBody)
}

func e07RateLimitBody(t *testing.T, dbType common.DatabaseType) {
	// E07 uses the shared Redis client because the limiter.New singleton
	// (sync.Once) permanently saves the first *redis.Client it receives.
	// The shared client lives for the entire process and is only closed
	// in TestMain.
	f := setupRelaySmoke(t, dbType, relayRedisSharedRateLimiter)

	// Save and restore the model request rate-limit globals.
	prevEnabled := setting.ModelRequestRateLimitEnabled
	prevDuration := setting.ModelRequestRateLimitDurationMinutes
	prevCount := setting.ModelRequestRateLimitCount
	prevSuccess := setting.ModelRequestRateLimitSuccessCount
	prevGroup := setting.ModelRequestRateLimitGroup2JSONString()
	t.Cleanup(func() {
		setting.ModelRequestRateLimitEnabled = prevEnabled
		setting.ModelRequestRateLimitDurationMinutes = prevDuration
		setting.ModelRequestRateLimitCount = prevCount
		setting.ModelRequestRateLimitSuccessCount = prevSuccess
		if err := setting.UpdateModelRequestRateLimitGroupByJSONString(prevGroup); err != nil {
			t.Errorf("restore rate limit group: %v", err)
		}
	})

	// Deterministic Redis rate limit: allow 1 total request in a 1-minute
	// window, so the first request is allowed and the second is rejected
	// with exactly 429 before any billing. The rate limiter middleware
	// checks common.RedisEnabled and uses common.RDB (the miniredis
	// instance created by setupRelaySmoke).
	setting.ModelRequestRateLimitEnabled = true
	setting.ModelRequestRateLimitDurationMinutes = 1
	setting.ModelRequestRateLimitCount = 1
	setting.ModelRequestRateLimitSuccessCount = 1000
	require.NoError(t, setting.UpdateModelRequestRateLimitGroupByJSONString(`{}`))

	// Deterministic user identity (isolated from other tests).
	ckpt := f.tracker.checkpoint()
	first := doRequest(f, f.tokenKey, chatBody(t, false))
	require.True(t, waitUpstreamHit(f.upstreamCh, 1), "first request must reach upstream")
	require.Equal(t, http.StatusOK, first.Code, "first request must be 2xx, body=%s", first.Body.String())
	assert.Equal(t, int64(1), f.upstreamHit.Load(), "first request hits upstream once")
	assert.Equal(t, relaySmokeFinalUserQuota, readUserQuota(t, f.userID), "first request settles exactly 25")
	assert.Equal(t, int64(1), countUserLogs(t, f.userID), "first request writes exactly one log")

	// Wait for first request's async Redis events (rate-limit, token-cache,
	// user-cache, performance) before issuing the second request.
	awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
		{Category: p10RedisCatRateLimitWrite, Count: 1},
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})

	// Second request: rate-limited. Uses its own checkpoint.
	ckpt2 := f.tracker.checkpoint()
	second := doRequest(f, f.tokenKey, chatBody(t, false))
	require.Equal(t, http.StatusTooManyRequests, second.Code,
		"second request must be exactly 429, got %d", second.Code)
	assert.Equal(t, int64(1), f.upstreamHit.Load(),
		"second request must not reach the upstream (hit stays 1)")
	assert.Equal(t, relaySmokeFinalUserQuota, readUserQuota(t, f.userID),
		"second request must not change user quota")
	remain, used := readTokenQuota(t, f.userID)
	assert.Equal(t, relaySmokeTokenQuota-relaySmokeExpectedCost, remain,
		"second request must not change token remain")
	assert.Equal(t, relaySmokeExpectedCost, used, "second request must not change token used")
	assert.Equal(t, int64(1), countUserLogs(t, f.userID),
		"second request must not add a consume log")

	// Wait for the rate-limit-write event from the 429 path, then snapshot
	// the ledger and assert no billing writes (user-write, perf-write,
	// token-write) occurred.
	awaitRelayAsync(t, f, ckpt2, []p10WaitRequirement{
		{Category: p10RedisCatRateLimitWrite, Count: 1},
	})
	snap := snapshotAfter(f, ckpt2)
	assertNoBillingWrites(t, snap)
}

// --- E08 no upstream key leak ---

func TestRelaySmokeE08_NoUpstreamKeyLeak(t *testing.T) {
	p10RunAcrossDatabases(t, "E08", e08NoLeakBody)
}

func e08NoLeakBody(t *testing.T, dbType common.DatabaseType) {
	f := setupRelaySmoke(t, dbType, relayRedisPerTest)
	ckpt := f.tracker.checkpoint()
	rec := doRequest(f, f.tokenKey, chatBody(t, false))
	require.True(t, waitUpstreamHit(f.upstreamCh, 1), "upstream must be hit")
	require.Equal(t, http.StatusOK, rec.Code, "success must be 200")

	// Prove at least one real consume log exists.
	var logs []model.Log
	require.NoError(t, model.DB.Where("user_id = ?", f.userID).Find(&logs).Error)
	require.NotEmpty(t, logs, "at least one real consume log must exist")

	assertNoUpstreamKeyLeak(t, rec.Body.String(), rec.Header(), logs)
	assert.NotContains(t, rec.Body.String(), f.tokenKey, "response must not echo the token")

	awaitRelayAsync(t, f, ckpt, []p10WaitRequirement{
		{Category: p10RedisCatTokenQuotaWrite, Count: 1},
		{Category: p10RedisCatUserQuotaWrite, Count: 1},
		{Category: p10RedisCatPerfWrite, Count: 1},
	})
}
